### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by pmgrv**
To Division at Center
Added Class at body

### CODE REVIEW

**Review by NeverGiveUpChetan — APPROVED** [review]

**Comment by NeverGiveUpChetan** [comment]
Changes are okay

**Comment by pmgrv** [comment]
Verified from Chetan

**Comment by pmgrv** [comment]
Need to be merged

**Comment by NeverGiveUpChetan** [comment]
Approved

**Review by NeverGiveUpChetan — APPROVED** [review]

**Review by pmgrv — COMMENTED** [review]
Approved from Chetan

**Review by NeverGiveUpChetan — APPROVED** [review]
Changes are okay to be merged

**Review by pmgrv — COMMENTED** [review]
Thanks

**Review by pmgrv — COMMENTED** [review]
Thanks again

**Comment by pmgrv** [comment]
Merging

**Review by NeverGiveUpChetan — APPROVED** [review]
Approved again

**Review by pmgrv — COMMENTED** [review]
Done

**Pull request merged**
